# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.14.4 is version 28
loaderVersion="[28,)"
# A URL to refer people to when problems occur with this mod
# issueTrackerURL="github.com/MinecraftForge/MinecraftForge/issues"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false

[[mods]]
  modId="terragen"
  version="1.0.0.0"
  displayName="Terragen"
  # updateJSONURL="minecraftforge.net/versions.json"
  # displayURL="minecraftforge.net"
  # logoFile="assets/terragen/textures/logo.png"
  # credits=""
  # authors=""
  # description='''
  # Lets you craft dirt into diamonds. This is a traditional mod that has existed for eons. It is ancient. The holy Notch created it. Jeb rainbowfied it. Dinnerbone made it upside down. Etc.
  # '''

  [[dependencies.terragen]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.terragen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
